version: "3.9"
services:

  mensajeria:
    build: ./build/mensajeria/
    volumes:
      - ./mensajeria:/mensajeria
    ports:
      - "5002:5000" 
    depends_on:
      - flask-app
    links:
      - flask-app

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock



  flask-app:
    build: ./build/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)" 
      - "traefik.http.services.app.loadbalancer.server.port=5000"
    volumes:
      - ./app:/app
    ports:
      - "5000:5000" 
    depends_on:
      - flask-api
    links:
      - flask-api

  flask-api:
    build: ./build/api/
    volumes:
      - ./api:/api
    ports:
      - "5001:5000" 
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql


  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "database"
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - datos_mysql:/var/lib/mysql
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    ports:
      - "8085:80" # Mapea el puerto 8080 para phpMyAdmin
    depends_on:
      - mysql


volumes:
  datos_mysql: