version: "3.9"
services:
  flask-app:
    build: ./build/app/
    volumes:
      - ./app:/app
    ports:
      - "5000:5000" 
    depends_on:
      - flask-api
    links:
      - flask-api

  flask-api:
    build: ./build/api/
    volumes:
      - ./api:/api
    ports:
      - "5001:5000" 
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql

  mensajeria:
    build: ./build/mensajeria/
    volumes:
      - ./mensajeria:/mensajeria
    ports:
      - "5002:5000" 
    depends_on:
      - flask-api
    links:
      - flask-api


  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "database"
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - datos_mysql:/var/lib/mysql
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    ports:
      - "8080:80" # Mapea el puerto 8080 para phpMyAdmin
    depends_on:
      - mysql


volumes:
  datos_mysql: