apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "VoQvmfovsy0hb0CcN5SI"
        - name: MYSQL_DATABASE
          value: "database"
       
---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-bd
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306