apiVersion: apps/v1
kind: Deployment
metadata:
  name: mensajeria-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mensajeria
  template:
    metadata:
      labels:
        component: mensajeria
    spec:
      containers:
      - name: mensajeria
        image: maits27/mensajeria
        ports:
        - containerPort: 5002

---


apiVersion: v1
kind: Service
metadata:
  name: clusterip-mensajeria
spec:
  type: ClusterIP
  selector:
    component: mensajeria
  ports:
  - port: 5002
    targetPort: 5002