apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-configmap
        volumeMounts:
        - name: initial-data
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: initial-data
        configMap:
          name: mysql-configmap
       
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306