apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
      - name: app
        image: maits27/app
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_API_HOST
            value: flask-api
          - name: MENSAJERIA_HOST
            value: mensajeria


---

apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: ClusterIP
  selector:
    component: app
  ports:
  - port: 5000
    targetPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: app-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    component: app