apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: api
        image: maits27/api
        ports:
        - containerPort: 5001
        env:
          - name: MYSQL_HOST
            value: mysql
        
---


apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
  - port: 5001
    targetPort: 5001